services:
  app:
    build: .
    restart: always
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timecard
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
