services:
  app:
    build: .
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timecard
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
